package model;
// Generated Nov 7, 2018 7:02:43 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Group generated by hbm2java
 */
public class Group  implements java.io.Serializable {


     private Integer groupId;
     private String groupName;
     private Integer accessLevel;
     private Set users = new HashSet(0);

    public Group() {
    }

    public Group(String groupName, Integer accessLevel, Set users) {
       this.groupName = groupName;
       this.accessLevel = accessLevel;
       this.users = users;
    }
   
    public Integer getGroupId() {
        return this.groupId;
    }
    
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }
    public String getGroupName() {
        return this.groupName;
    }
    
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }
    public Integer getAccessLevel() {
        return this.accessLevel;
    }
    
    public void setAccessLevel(Integer accessLevel) {
        this.accessLevel = accessLevel;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }




}


